Upgrade map-age-cleaner dependency
SamVerschueren/expiry-map pull request #3
Opened 2021-10-16 08:27 UTC by lkosipov

This PR upgrades map-age-cleaner to the latest version, primarily for https://github.com/SamVerschueren/map-age-cleaner/pull/7. It could seem negligible at first, since expiry-map starts to be recommended by the popular [p-memoize](https://www.npmjs.com/package/p-memoize), I think a lot people will consider using expiry-map and they could benefit from this change.

2021-12-12 14:26 UTC, lkosipov commented
Hi @SamVerschueren, any chance of merging this PR off? I guess it won't take much time :)

2022-02-05 18:27 UTC, SamVerschueren requested changes
Sorry 🙈 .

2022-02-05 18:27 UTC, SamVerschueren commented on .travis.yml
> +  - '7.6'
I don't care about non-lts versions. Drop this and add 12, 14 and 16 as well.

2022-02-05 18:27 UTC, SamVerschueren commented on package.json
> +		"node": ">=7.6"
```suggestion
		"node": ">=8"
```

2022-02-07 05:50 UTC, lkosipov commented
So glad you finally reviewed this! Node.js v10 is also no longer supported. So [the oldest LTS version that is supported is now v12](https://nodejs.org/en/about/releases/).

2022-02-07 06:15 UTC, lkosipov commented
Sorry I may have misunderstood you. It should be what you want now...

2022-02-08 12:30 UTC, SamVerschueren approved these changes

2022-02-08 12:30 UTC, merged

2022-02-08 12:43 UTC, SamVerschueren commented
Merged and released 🙏 !